
server:
  port: 8888
  context-path: /spring-boot-gradle

#数据库配置
postgres:
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: #java021
  url: jdbc:postgresql://localhost:5432/b2g_test
  max-active: 10
spring:
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    content-type: text/html
    suffix: .html
    request-context-attribute: req
    expose-request-attributes: true
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    charset: UTF-8
    allow-request-override: true
    allow-session-override: true
    enabled: true
failure:
  failure-mapping:
      com.travelzen.sbg.exception.MyUserLoginException: /login?message=passwordFailed